/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCodeRouteImport } from './routes/auth/code'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedNamespaceProvisionRouteImport } from './routes/_authenticated/namespace/provision'
import { Route as AuthenticatedNamespaceNamespaceRouteRouteImport } from './routes/_authenticated/namespace/$namespace/route'
import { Route as AuthenticatedNamespaceNamespaceIndexRouteImport } from './routes/_authenticated/namespace/$namespace/index'
import { Route as AuthenticatedNamespaceNamespaceMembersRouteImport } from './routes/_authenticated/namespace/$namespace/members'
import { Route as AuthenticatedNamespaceNamespaceInvitationsRouteImport } from './routes/_authenticated/namespace/$namespace/invitations'
import { Route as AuthenticatedNamespaceNamespaceKmsRouteRouteImport } from './routes/_authenticated/namespace/$namespace/kms/route'
import { Route as AuthenticatedNamespaceNamespaceSettingsIndexRouteImport } from './routes/_authenticated/namespace/$namespace/settings/index'
import { Route as AuthenticatedNamespaceNamespaceKmsIndexRouteImport } from './routes/_authenticated/namespace/$namespace/kms/index'
import { Route as AuthenticatedNamespaceNamespaceKmsCreateRouteImport } from './routes/_authenticated/namespace/$namespace/kms/create'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceRouteRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/route'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceIndexRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/index'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceSettingsRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/settings'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/create-profile'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/requests/index'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/profiles/$profile'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCodeRoute = AuthCodeRouteImport.update({
  id: '/auth/code',
  path: '/auth/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNamespaceProvisionRoute =
  AuthenticatedNamespaceProvisionRouteImport.update({
    id: '/namespace/provision',
    path: '/namespace/provision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceRouteRoute =
  AuthenticatedNamespaceNamespaceRouteRouteImport.update({
    id: '/namespace/$namespace',
    path: '/namespace/$namespace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceIndexRoute =
  AuthenticatedNamespaceNamespaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceMembersRoute =
  AuthenticatedNamespaceNamespaceMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceInvitationsRoute =
  AuthenticatedNamespaceNamespaceInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceKmsRouteRoute =
  AuthenticatedNamespaceNamespaceKmsRouteRouteImport.update({
    id: '/kms',
    path: '/kms',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceSettingsIndexRoute =
  AuthenticatedNamespaceNamespaceSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceKmsIndexRoute =
  AuthenticatedNamespaceNamespaceKmsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceKmsRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceKmsCreateRoute =
  AuthenticatedNamespaceNamespaceKmsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedNamespaceNamespaceKmsRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceServicesServiceRouteRoute =
  AuthenticatedNamespaceNamespaceServicesServiceRouteRouteImport.update({
    id: '/services/$service',
    path: '/services/$service',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceServicesServiceIndexRoute =
  AuthenticatedNamespaceNamespaceServicesServiceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute =
  AuthenticatedNamespaceNamespaceServicesServiceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () =>
      AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute =
  AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRouteImport.update(
    {
      id: '/create-profile',
      path: '/create-profile',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute =
  AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRouteImport.update(
    {
      id: '/requests/',
      path: '/requests/',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRoute =
  AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteImport.update(
    {
      id: '/profiles/$profile',
      path: '/profiles/$profile',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/api/$': typeof ApiSplatRoute
  '/auth/code': typeof AuthCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/namespace/$namespace': typeof AuthenticatedNamespaceNamespaceRouteRouteWithChildren
  '/namespace/provision': typeof AuthenticatedNamespaceProvisionRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/namespace/$namespace/kms': typeof AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren
  '/namespace/$namespace/invitations': typeof AuthenticatedNamespaceNamespaceInvitationsRoute
  '/namespace/$namespace/members': typeof AuthenticatedNamespaceNamespaceMembersRoute
  '/namespace/$namespace/': typeof AuthenticatedNamespaceNamespaceIndexRoute
  '/namespace/$namespace/services/$service': typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren
  '/namespace/$namespace/kms/create': typeof AuthenticatedNamespaceNamespaceKmsCreateRoute
  '/namespace/$namespace/kms/': typeof AuthenticatedNamespaceNamespaceKmsIndexRoute
  '/namespace/$namespace/settings': typeof AuthenticatedNamespaceNamespaceSettingsIndexRoute
  '/namespace/$namespace/services/$service/create-profile': typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute
  '/namespace/$namespace/services/$service/settings': typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute
  '/namespace/$namespace/services/$service/': typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRoute
  '/namespace/$namespace/services/$service/profiles/$profile': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRoute
  '/namespace/$namespace/services/$service/requests': typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/auth/code': typeof AuthCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/namespace/provision': typeof AuthenticatedNamespaceProvisionRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/namespace/$namespace/invitations': typeof AuthenticatedNamespaceNamespaceInvitationsRoute
  '/namespace/$namespace/members': typeof AuthenticatedNamespaceNamespaceMembersRoute
  '/namespace/$namespace': typeof AuthenticatedNamespaceNamespaceIndexRoute
  '/namespace/$namespace/kms/create': typeof AuthenticatedNamespaceNamespaceKmsCreateRoute
  '/namespace/$namespace/kms': typeof AuthenticatedNamespaceNamespaceKmsIndexRoute
  '/namespace/$namespace/settings': typeof AuthenticatedNamespaceNamespaceSettingsIndexRoute
  '/namespace/$namespace/services/$service/create-profile': typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute
  '/namespace/$namespace/services/$service/settings': typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute
  '/namespace/$namespace/services/$service': typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRoute
  '/namespace/$namespace/services/$service/profiles/$profile': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRoute
  '/namespace/$namespace/services/$service/requests': typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/code': typeof AuthCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/namespace/$namespace': typeof AuthenticatedNamespaceNamespaceRouteRouteWithChildren
  '/_authenticated/namespace/provision': typeof AuthenticatedNamespaceProvisionRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/namespace/$namespace/kms': typeof AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/invitations': typeof AuthenticatedNamespaceNamespaceInvitationsRoute
  '/_authenticated/namespace/$namespace/members': typeof AuthenticatedNamespaceNamespaceMembersRoute
  '/_authenticated/namespace/$namespace/': typeof AuthenticatedNamespaceNamespaceIndexRoute
  '/_authenticated/namespace/$namespace/services/$service': typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/kms/create': typeof AuthenticatedNamespaceNamespaceKmsCreateRoute
  '/_authenticated/namespace/$namespace/kms/': typeof AuthenticatedNamespaceNamespaceKmsIndexRoute
  '/_authenticated/namespace/$namespace/settings/': typeof AuthenticatedNamespaceNamespaceSettingsIndexRoute
  '/_authenticated/namespace/$namespace/services/$service/create-profile': typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute
  '/_authenticated/namespace/$namespace/services/$service/settings': typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute
  '/_authenticated/namespace/$namespace/services/$service/': typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRoute
  '/_authenticated/namespace/$namespace/services/$service/profiles/$profile': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRoute
  '/_authenticated/namespace/$namespace/services/$service/requests/': typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/$'
    | '/auth/code'
    | '/'
    | '/namespace/$namespace'
    | '/namespace/provision'
    | '/account'
    | '/namespace/$namespace/kms'
    | '/namespace/$namespace/invitations'
    | '/namespace/$namespace/members'
    | '/namespace/$namespace/'
    | '/namespace/$namespace/services/$service'
    | '/namespace/$namespace/kms/create'
    | '/namespace/$namespace/kms/'
    | '/namespace/$namespace/settings'
    | '/namespace/$namespace/services/$service/create-profile'
    | '/namespace/$namespace/services/$service/settings'
    | '/namespace/$namespace/services/$service/'
    | '/namespace/$namespace/services/$service/profiles/$profile'
    | '/namespace/$namespace/services/$service/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/$'
    | '/auth/code'
    | '/'
    | '/namespace/provision'
    | '/account'
    | '/namespace/$namespace/invitations'
    | '/namespace/$namespace/members'
    | '/namespace/$namespace'
    | '/namespace/$namespace/kms/create'
    | '/namespace/$namespace/kms'
    | '/namespace/$namespace/settings'
    | '/namespace/$namespace/services/$service/create-profile'
    | '/namespace/$namespace/services/$service/settings'
    | '/namespace/$namespace/services/$service'
    | '/namespace/$namespace/services/$service/profiles/$profile'
    | '/namespace/$namespace/services/$service/requests'
  id:
    | '__root__'
    | '/_authenticated'
    | '/api/$'
    | '/auth/code'
    | '/_authenticated/'
    | '/_authenticated/namespace/$namespace'
    | '/_authenticated/namespace/provision'
    | '/_authenticated/account/'
    | '/_authenticated/namespace/$namespace/kms'
    | '/_authenticated/namespace/$namespace/invitations'
    | '/_authenticated/namespace/$namespace/members'
    | '/_authenticated/namespace/$namespace/'
    | '/_authenticated/namespace/$namespace/services/$service'
    | '/_authenticated/namespace/$namespace/kms/create'
    | '/_authenticated/namespace/$namespace/kms/'
    | '/_authenticated/namespace/$namespace/settings/'
    | '/_authenticated/namespace/$namespace/services/$service/create-profile'
    | '/_authenticated/namespace/$namespace/services/$service/settings'
    | '/_authenticated/namespace/$namespace/services/$service/'
    | '/_authenticated/namespace/$namespace/services/$service/profiles/$profile'
    | '/_authenticated/namespace/$namespace/services/$service/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  AuthCodeRoute: typeof AuthCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/code': {
      id: '/auth/code'
      path: '/auth/code'
      fullPath: '/auth/code'
      preLoaderRoute: typeof AuthCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/namespace/provision': {
      id: '/_authenticated/namespace/provision'
      path: '/namespace/provision'
      fullPath: '/namespace/provision'
      preLoaderRoute: typeof AuthenticatedNamespaceProvisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/namespace/$namespace': {
      id: '/_authenticated/namespace/$namespace'
      path: '/namespace/$namespace'
      fullPath: '/namespace/$namespace'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/namespace/$namespace/': {
      id: '/_authenticated/namespace/$namespace/'
      path: '/'
      fullPath: '/namespace/$namespace/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/members': {
      id: '/_authenticated/namespace/$namespace/members'
      path: '/members'
      fullPath: '/namespace/$namespace/members'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceMembersRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/invitations': {
      id: '/_authenticated/namespace/$namespace/invitations'
      path: '/invitations'
      fullPath: '/namespace/$namespace/invitations'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceInvitationsRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/kms': {
      id: '/_authenticated/namespace/$namespace/kms'
      path: '/kms'
      fullPath: '/namespace/$namespace/kms'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceKmsRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/settings/': {
      id: '/_authenticated/namespace/$namespace/settings/'
      path: '/settings'
      fullPath: '/namespace/$namespace/settings'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/kms/': {
      id: '/_authenticated/namespace/$namespace/kms/'
      path: '/'
      fullPath: '/namespace/$namespace/kms/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceKmsIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceKmsRouteRoute
    }
    '/_authenticated/namespace/$namespace/kms/create': {
      id: '/_authenticated/namespace/$namespace/kms/create'
      path: '/create'
      fullPath: '/namespace/$namespace/kms/create'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceKmsCreateRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceKmsRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service': {
      id: '/_authenticated/namespace/$namespace/services/$service'
      path: '/services/$service'
      fullPath: '/namespace/$namespace/services/$service'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/': {
      id: '/_authenticated/namespace/$namespace/services/$service/'
      path: '/'
      fullPath: '/namespace/$namespace/services/$service/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/settings': {
      id: '/_authenticated/namespace/$namespace/services/$service/settings'
      path: '/settings'
      fullPath: '/namespace/$namespace/services/$service/settings'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/create-profile': {
      id: '/_authenticated/namespace/$namespace/services/$service/create-profile'
      path: '/create-profile'
      fullPath: '/namespace/$namespace/services/$service/create-profile'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/requests/': {
      id: '/_authenticated/namespace/$namespace/services/$service/requests/'
      path: '/requests'
      fullPath: '/namespace/$namespace/services/$service/requests'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/profiles/$profile': {
      id: '/_authenticated/namespace/$namespace/services/$service/profiles/$profile'
      path: '/profiles/$profile'
      fullPath: '/namespace/$namespace/services/$service/profiles/$profile'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
  }
}

interface AuthenticatedNamespaceNamespaceKmsRouteRouteChildren {
  AuthenticatedNamespaceNamespaceKmsCreateRoute: typeof AuthenticatedNamespaceNamespaceKmsCreateRoute
  AuthenticatedNamespaceNamespaceKmsIndexRoute: typeof AuthenticatedNamespaceNamespaceKmsIndexRoute
}

const AuthenticatedNamespaceNamespaceKmsRouteRouteChildren: AuthenticatedNamespaceNamespaceKmsRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceKmsCreateRoute:
      AuthenticatedNamespaceNamespaceKmsCreateRoute,
    AuthenticatedNamespaceNamespaceKmsIndexRoute:
      AuthenticatedNamespaceNamespaceKmsIndexRoute,
  }

const AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceKmsRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceKmsRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceServicesServiceRouteRouteChildren {
  AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute
  AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute
  AuthenticatedNamespaceNamespaceServicesServiceIndexRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRoute
  AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRoute
  AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute
}

const AuthenticatedNamespaceNamespaceServicesServiceRouteRouteChildren: AuthenticatedNamespaceNamespaceServicesServiceRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute:
      AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute,
    AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute:
      AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute,
    AuthenticatedNamespaceNamespaceServicesServiceIndexRoute:
      AuthenticatedNamespaceNamespaceServicesServiceIndexRoute,
    AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRoute:
      AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRoute,
    AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute:
      AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute,
  }

const AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceServicesServiceRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceServicesServiceRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceRouteRouteChildren {
  AuthenticatedNamespaceNamespaceKmsRouteRoute: typeof AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceInvitationsRoute: typeof AuthenticatedNamespaceNamespaceInvitationsRoute
  AuthenticatedNamespaceNamespaceMembersRoute: typeof AuthenticatedNamespaceNamespaceMembersRoute
  AuthenticatedNamespaceNamespaceIndexRoute: typeof AuthenticatedNamespaceNamespaceIndexRoute
  AuthenticatedNamespaceNamespaceServicesServiceRouteRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceSettingsIndexRoute: typeof AuthenticatedNamespaceNamespaceSettingsIndexRoute
}

const AuthenticatedNamespaceNamespaceRouteRouteChildren: AuthenticatedNamespaceNamespaceRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceKmsRouteRoute:
      AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceInvitationsRoute:
      AuthenticatedNamespaceNamespaceInvitationsRoute,
    AuthenticatedNamespaceNamespaceMembersRoute:
      AuthenticatedNamespaceNamespaceMembersRoute,
    AuthenticatedNamespaceNamespaceIndexRoute:
      AuthenticatedNamespaceNamespaceIndexRoute,
    AuthenticatedNamespaceNamespaceServicesServiceRouteRoute:
      AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceSettingsIndexRoute:
      AuthenticatedNamespaceNamespaceSettingsIndexRoute,
  }

const AuthenticatedNamespaceNamespaceRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedNamespaceNamespaceRouteRoute: typeof AuthenticatedNamespaceNamespaceRouteRouteWithChildren
  AuthenticatedNamespaceProvisionRoute: typeof AuthenticatedNamespaceProvisionRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedNamespaceNamespaceRouteRoute:
    AuthenticatedNamespaceNamespaceRouteRouteWithChildren,
  AuthenticatedNamespaceProvisionRoute: AuthenticatedNamespaceProvisionRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  AuthCodeRoute: AuthCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
