/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthCodeRouteImport } from './routes/auth/code'
import { Route as AuthScopesRouteImport } from './routes/auth/scopes'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedJoinKeyRouteImport } from './routes/_authenticated/join/$key'
import { Route as AuthenticatedNamespaceNamespaceRouteRouteImport } from './routes/_authenticated/namespace/$namespace/route'
import { Route as AuthenticatedNamespaceProvisionRouteImport } from './routes/_authenticated/namespace/provision'
import { Route as AuthenticatedNamespaceNamespaceOverviewRouteRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/route'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryRouteRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/route'
import { Route as AuthenticatedNamespaceNamespaceKmsRouteRouteImport } from './routes/_authenticated/namespace/$namespace/kms/route'
import { Route as AuthenticatedNamespaceNamespaceServicesRouteRouteImport } from './routes/_authenticated/namespace/$namespace/services/route'
import { Route as AuthenticatedNamespaceNamespaceOverviewIndexRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/index'
import { Route as AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/applications/route'
import { Route as AuthenticatedNamespaceNamespaceOverviewInvitationsRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/invitations'
import { Route as AuthenticatedNamespaceNamespaceOverviewMembersRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/members'
import { Route as AuthenticatedNamespaceNamespaceKmsIndexRouteImport } from './routes/_authenticated/namespace/$namespace/kms/index'
import { Route as AuthenticatedNamespaceNamespaceKmsKeysetRouteImport } from './routes/_authenticated/namespace/$namespace/kms/$keyset'
import { Route as AuthenticatedNamespaceNamespaceKmsCreateRouteImport } from './routes/_authenticated/namespace/$namespace/kms/create'
import { Route as AuthenticatedNamespaceNamespaceServicesIndexRouteImport } from './routes/_authenticated/namespace/$namespace/services/index'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceRouteRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/route'
import { Route as AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/applications/index'
import { Route as AuthenticatedNamespaceNamespaceOverviewApplicationsIdRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/applications/$id'
import { Route as AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/applications/create'
import { Route as AuthenticatedNamespaceNamespaceOverviewAuditIndexRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/audit/index'
import { Route as AuthenticatedNamespaceNamespaceOverviewSettingsIndexRouteImport } from './routes/_authenticated/namespace/$namespace/_overview/settings/index'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/groups/index'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/groups/$groupId/route'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/groups/create'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/registry/index'
import { Route as AuthenticatedNamespaceNamespaceArtifactorySearchIndexRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/search/index'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/transfers/index'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/transfers/$transferId/route'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/transfers/create'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceIndexRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/index'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/create-profile'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/manifest/route'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceSettingsRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/settings'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/groups/$groupId/index'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/groups/$groupId/edit'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/route'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/transfers/$transferId/index'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/manifest/index'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/manifest/artifacts'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/profiles/$profile/route'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/requests/index'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/index'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/profiles/$profile/index'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/profiles/$profile/history'
import { Route as AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRouteImport } from './routes/_authenticated/namespace/$namespace/services/$service/requests/$number/index'
import { Route as AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRouteImport } from './routes/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCodeRoute = AuthCodeRouteImport.update({
  id: '/auth/code',
  path: '/auth/code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthScopesRoute = AuthScopesRouteImport.update({
  id: '/auth/scopes',
  path: '/auth/scopes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJoinKeyRoute = AuthenticatedJoinKeyRouteImport.update({
  id: '/join/$key',
  path: '/join/$key',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNamespaceNamespaceRouteRoute =
  AuthenticatedNamespaceNamespaceRouteRouteImport.update({
    id: '/namespace/$namespace',
    path: '/namespace/$namespace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNamespaceProvisionRoute =
  AuthenticatedNamespaceProvisionRouteImport.update({
    id: '/namespace/provision',
    path: '/namespace/provision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewRouteRoute =
  AuthenticatedNamespaceNamespaceOverviewRouteRouteImport.update({
    id: '/_overview',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceArtifactoryRouteRoute =
  AuthenticatedNamespaceNamespaceArtifactoryRouteRouteImport.update({
    id: '/artifactory',
    path: '/artifactory',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceKmsRouteRoute =
  AuthenticatedNamespaceNamespaceKmsRouteRouteImport.update({
    id: '/kms',
    path: '/kms',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceServicesRouteRoute =
  AuthenticatedNamespaceNamespaceServicesRouteRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedNamespaceNamespaceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewIndexRoute =
  AuthenticatedNamespaceNamespaceOverviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceOverviewRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute =
  AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedNamespaceNamespaceOverviewRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewInvitationsRoute =
  AuthenticatedNamespaceNamespaceOverviewInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedNamespaceNamespaceOverviewRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewMembersRoute =
  AuthenticatedNamespaceNamespaceOverviewMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedNamespaceNamespaceOverviewRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceKmsIndexRoute =
  AuthenticatedNamespaceNamespaceKmsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceKmsRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceKmsKeysetRoute =
  AuthenticatedNamespaceNamespaceKmsKeysetRouteImport.update({
    id: '/$keyset',
    path: '/$keyset',
    getParentRoute: () => AuthenticatedNamespaceNamespaceKmsRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceKmsCreateRoute =
  AuthenticatedNamespaceNamespaceKmsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedNamespaceNamespaceKmsRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceServicesIndexRoute =
  AuthenticatedNamespaceNamespaceServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceServicesRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceServicesServiceRouteRoute =
  AuthenticatedNamespaceNamespaceServicesServiceRouteRouteImport.update({
    id: '/$service',
    path: '/$service',
    getParentRoute: () => AuthenticatedNamespaceNamespaceServicesRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRoute =
  AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewApplicationsIdRoute =
  AuthenticatedNamespaceNamespaceOverviewApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () =>
      AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRoute =
  AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () =>
      AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewAuditIndexRoute =
  AuthenticatedNamespaceNamespaceOverviewAuditIndexRouteImport.update({
    id: '/audit/',
    path: '/audit/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceOverviewRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceOverviewSettingsIndexRoute =
  AuthenticatedNamespaceNamespaceOverviewSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceOverviewRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRoute =
  AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceArtifactoryRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRoute =
  AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteImport.update(
    {
      id: '/groups/$groupId',
      path: '/groups/$groupId',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceArtifactoryRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRoute =
  AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRouteImport.update({
    id: '/groups/create',
    path: '/groups/create',
    getParentRoute: () => AuthenticatedNamespaceNamespaceArtifactoryRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRoute =
  AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRouteImport.update({
    id: '/registry/',
    path: '/registry/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceArtifactoryRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceArtifactorySearchIndexRoute =
  AuthenticatedNamespaceNamespaceArtifactorySearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceArtifactoryRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRoute =
  AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRouteImport.update({
    id: '/transfers/',
    path: '/transfers/',
    getParentRoute: () => AuthenticatedNamespaceNamespaceArtifactoryRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRoute =
  AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteImport.update(
    {
      id: '/transfers/$transferId',
      path: '/transfers/$transferId',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceArtifactoryRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRoute =
  AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRouteImport.update({
    id: '/transfers/create',
    path: '/transfers/create',
    getParentRoute: () => AuthenticatedNamespaceNamespaceArtifactoryRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceServicesServiceIndexRoute =
  AuthenticatedNamespaceNamespaceServicesServiceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute =
  AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRouteImport.update(
    {
      id: '/create-profile',
      path: '/create-profile',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRoute =
  AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteImport.update(
    {
      id: '/manifest',
      path: '/manifest',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute =
  AuthenticatedNamespaceNamespaceServicesServiceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () =>
      AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
  } as any)
const AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRoute =
  AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRoute =
  AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRouteImport.update(
    {
      id: '/edit',
      path: '/edit',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRoute =
  AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteImport.update(
    {
      id: '/registry/$groupId/$artifactId',
      path: '/registry/$groupId/$artifactId',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceArtifactoryRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRoute =
  AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRoute =
  AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRoute =
  AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRouteImport.update(
    {
      id: '/artifacts',
      path: '/artifacts',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRoute =
  AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteImport.update(
    {
      id: '/profiles/$profile',
      path: '/profiles/$profile',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute =
  AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRouteImport.update(
    {
      id: '/requests/',
      path: '/requests/',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRoute =
  AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRoute =
  AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRoute =
  AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRouteImport.update(
    {
      id: '/history',
      path: '/history',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRoute =
  AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRouteImport.update(
    {
      id: '/requests/$number/',
      path: '/requests/$number/',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceServicesServiceRouteRoute,
    } as any,
  )
const AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRoute =
  AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRouteImport.update(
    {
      id: '/$version/',
      path: '/$version/',
      getParentRoute: () =>
        AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/error': typeof ErrorRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/code': typeof AuthCodeRoute
  '/auth/scopes': typeof AuthScopesRoute
  '/namespace/$namespace': typeof AuthenticatedNamespaceNamespaceRouteRouteWithChildren
  '/join/$key': typeof AuthenticatedJoinKeyRoute
  '/namespace/provision': typeof AuthenticatedNamespaceProvisionRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/namespace/$namespace/artifactory': typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRouteWithChildren
  '/namespace/$namespace/kms': typeof AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren
  '/namespace/$namespace/services': typeof AuthenticatedNamespaceNamespaceServicesRouteRouteWithChildren
  '/namespace/$namespace/applications': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteWithChildren
  '/namespace/$namespace/services/$service': typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren
  '/namespace/$namespace/invitations': typeof AuthenticatedNamespaceNamespaceOverviewInvitationsRoute
  '/namespace/$namespace/members': typeof AuthenticatedNamespaceNamespaceOverviewMembersRoute
  '/namespace/$namespace/kms/$keyset': typeof AuthenticatedNamespaceNamespaceKmsKeysetRoute
  '/namespace/$namespace/kms/create': typeof AuthenticatedNamespaceNamespaceKmsCreateRoute
  '/namespace/$namespace/': typeof AuthenticatedNamespaceNamespaceOverviewIndexRoute
  '/namespace/$namespace/kms/': typeof AuthenticatedNamespaceNamespaceKmsIndexRoute
  '/namespace/$namespace/services/': typeof AuthenticatedNamespaceNamespaceServicesIndexRoute
  '/namespace/$namespace/artifactory/groups/$groupId': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteWithChildren
  '/namespace/$namespace/artifactory/transfers/$transferId': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteWithChildren
  '/namespace/$namespace/services/$service/manifest': typeof AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteWithChildren
  '/namespace/$namespace/applications/$id': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIdRoute
  '/namespace/$namespace/applications/create': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRoute
  '/namespace/$namespace/artifactory/groups/create': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRoute
  '/namespace/$namespace/artifactory/transfers/create': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRoute
  '/namespace/$namespace/services/$service/create-profile': typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute
  '/namespace/$namespace/services/$service/settings': typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute
  '/namespace/$namespace/applications/': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRoute
  '/namespace/$namespace/audit/': typeof AuthenticatedNamespaceNamespaceOverviewAuditIndexRoute
  '/namespace/$namespace/settings/': typeof AuthenticatedNamespaceNamespaceOverviewSettingsIndexRoute
  '/namespace/$namespace/artifactory/groups/': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRoute
  '/namespace/$namespace/artifactory/registry/': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRoute
  '/namespace/$namespace/artifactory/search/': typeof AuthenticatedNamespaceNamespaceArtifactorySearchIndexRoute
  '/namespace/$namespace/artifactory/transfers/': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRoute
  '/namespace/$namespace/services/$service/': typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRoute
  '/namespace/$namespace/artifactory/registry/$groupId/$artifactId': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteWithChildren
  '/namespace/$namespace/services/$service/profiles/$profile': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteWithChildren
  '/namespace/$namespace/artifactory/groups/$groupId/edit': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRoute
  '/namespace/$namespace/services/$service/manifest/artifacts': typeof AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRoute
  '/namespace/$namespace/artifactory/groups/$groupId/': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRoute
  '/namespace/$namespace/artifactory/transfers/$transferId/': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRoute
  '/namespace/$namespace/services/$service/manifest/': typeof AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRoute
  '/namespace/$namespace/services/$service/requests/': typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute
  '/namespace/$namespace/services/$service/profiles/$profile/history': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRoute
  '/namespace/$namespace/artifactory/registry/$groupId/$artifactId/': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRoute
  '/namespace/$namespace/services/$service/profiles/$profile/': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRoute
  '/namespace/$namespace/services/$service/requests/$number/': typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRoute
  '/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version/': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/code': typeof AuthCodeRoute
  '/auth/scopes': typeof AuthScopesRoute
  '/': typeof AuthenticatedIndexRoute
  '/namespace/$namespace': typeof AuthenticatedNamespaceNamespaceOverviewIndexRoute
  '/join/$key': typeof AuthenticatedJoinKeyRoute
  '/namespace/provision': typeof AuthenticatedNamespaceProvisionRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/namespace/$namespace/artifactory': typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRouteWithChildren
  '/namespace/$namespace/invitations': typeof AuthenticatedNamespaceNamespaceOverviewInvitationsRoute
  '/namespace/$namespace/members': typeof AuthenticatedNamespaceNamespaceOverviewMembersRoute
  '/namespace/$namespace/kms/$keyset': typeof AuthenticatedNamespaceNamespaceKmsKeysetRoute
  '/namespace/$namespace/kms/create': typeof AuthenticatedNamespaceNamespaceKmsCreateRoute
  '/namespace/$namespace/kms': typeof AuthenticatedNamespaceNamespaceKmsIndexRoute
  '/namespace/$namespace/services': typeof AuthenticatedNamespaceNamespaceServicesIndexRoute
  '/namespace/$namespace/applications/$id': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIdRoute
  '/namespace/$namespace/applications/create': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRoute
  '/namespace/$namespace/artifactory/groups/create': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRoute
  '/namespace/$namespace/artifactory/transfers/create': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRoute
  '/namespace/$namespace/services/$service/create-profile': typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute
  '/namespace/$namespace/services/$service/settings': typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute
  '/namespace/$namespace/applications': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRoute
  '/namespace/$namespace/audit': typeof AuthenticatedNamespaceNamespaceOverviewAuditIndexRoute
  '/namespace/$namespace/settings': typeof AuthenticatedNamespaceNamespaceOverviewSettingsIndexRoute
  '/namespace/$namespace/artifactory/groups': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRoute
  '/namespace/$namespace/artifactory/registry': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRoute
  '/namespace/$namespace/artifactory/search': typeof AuthenticatedNamespaceNamespaceArtifactorySearchIndexRoute
  '/namespace/$namespace/artifactory/transfers': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRoute
  '/namespace/$namespace/services/$service': typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRoute
  '/namespace/$namespace/artifactory/groups/$groupId/edit': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRoute
  '/namespace/$namespace/services/$service/manifest/artifacts': typeof AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRoute
  '/namespace/$namespace/artifactory/groups/$groupId': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRoute
  '/namespace/$namespace/artifactory/transfers/$transferId': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRoute
  '/namespace/$namespace/services/$service/manifest': typeof AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRoute
  '/namespace/$namespace/services/$service/requests': typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute
  '/namespace/$namespace/services/$service/profiles/$profile/history': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRoute
  '/namespace/$namespace/artifactory/registry/$groupId/$artifactId': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRoute
  '/namespace/$namespace/services/$service/profiles/$profile': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRoute
  '/namespace/$namespace/services/$service/requests/$number': typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRoute
  '/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/code': typeof AuthCodeRoute
  '/auth/scopes': typeof AuthScopesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/namespace/$namespace': typeof AuthenticatedNamespaceNamespaceRouteRouteWithChildren
  '/_authenticated/join/$key': typeof AuthenticatedJoinKeyRoute
  '/_authenticated/namespace/provision': typeof AuthenticatedNamespaceProvisionRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/namespace/$namespace/_overview': typeof AuthenticatedNamespaceNamespaceOverviewRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/artifactory': typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/kms': typeof AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/services': typeof AuthenticatedNamespaceNamespaceServicesRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/_overview/applications': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/services/$service': typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/_overview/invitations': typeof AuthenticatedNamespaceNamespaceOverviewInvitationsRoute
  '/_authenticated/namespace/$namespace/_overview/members': typeof AuthenticatedNamespaceNamespaceOverviewMembersRoute
  '/_authenticated/namespace/$namespace/kms/$keyset': typeof AuthenticatedNamespaceNamespaceKmsKeysetRoute
  '/_authenticated/namespace/$namespace/kms/create': typeof AuthenticatedNamespaceNamespaceKmsCreateRoute
  '/_authenticated/namespace/$namespace/_overview/': typeof AuthenticatedNamespaceNamespaceOverviewIndexRoute
  '/_authenticated/namespace/$namespace/kms/': typeof AuthenticatedNamespaceNamespaceKmsIndexRoute
  '/_authenticated/namespace/$namespace/services/': typeof AuthenticatedNamespaceNamespaceServicesIndexRoute
  '/_authenticated/namespace/$namespace/artifactory/groups/$groupId': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/artifactory/transfers/$transferId': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/services/$service/manifest': typeof AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/_overview/applications/$id': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIdRoute
  '/_authenticated/namespace/$namespace/_overview/applications/create': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRoute
  '/_authenticated/namespace/$namespace/artifactory/groups/create': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRoute
  '/_authenticated/namespace/$namespace/artifactory/transfers/create': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRoute
  '/_authenticated/namespace/$namespace/services/$service/create-profile': typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute
  '/_authenticated/namespace/$namespace/services/$service/settings': typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute
  '/_authenticated/namespace/$namespace/_overview/applications/': typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRoute
  '/_authenticated/namespace/$namespace/_overview/audit/': typeof AuthenticatedNamespaceNamespaceOverviewAuditIndexRoute
  '/_authenticated/namespace/$namespace/_overview/settings/': typeof AuthenticatedNamespaceNamespaceOverviewSettingsIndexRoute
  '/_authenticated/namespace/$namespace/artifactory/groups/': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRoute
  '/_authenticated/namespace/$namespace/artifactory/registry/': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRoute
  '/_authenticated/namespace/$namespace/artifactory/search/': typeof AuthenticatedNamespaceNamespaceArtifactorySearchIndexRoute
  '/_authenticated/namespace/$namespace/artifactory/transfers/': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRoute
  '/_authenticated/namespace/$namespace/services/$service/': typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRoute
  '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/services/$service/profiles/$profile': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteWithChildren
  '/_authenticated/namespace/$namespace/artifactory/groups/$groupId/edit': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRoute
  '/_authenticated/namespace/$namespace/services/$service/manifest/artifacts': typeof AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRoute
  '/_authenticated/namespace/$namespace/artifactory/groups/$groupId/': typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRoute
  '/_authenticated/namespace/$namespace/artifactory/transfers/$transferId/': typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRoute
  '/_authenticated/namespace/$namespace/services/$service/manifest/': typeof AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRoute
  '/_authenticated/namespace/$namespace/services/$service/requests/': typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute
  '/_authenticated/namespace/$namespace/services/$service/profiles/$profile/history': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRoute
  '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRoute
  '/_authenticated/namespace/$namespace/services/$service/profiles/$profile/': typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRoute
  '/_authenticated/namespace/$namespace/services/$service/requests/$number/': typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRoute
  '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version/': typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/invitations'
    | '/api/$'
    | '/auth/code'
    | '/auth/scopes'
    | '/namespace/$namespace'
    | '/join/$key'
    | '/namespace/provision'
    | '/account/'
    | '/namespace/$namespace/artifactory'
    | '/namespace/$namespace/kms'
    | '/namespace/$namespace/services'
    | '/namespace/$namespace/applications'
    | '/namespace/$namespace/services/$service'
    | '/namespace/$namespace/invitations'
    | '/namespace/$namespace/members'
    | '/namespace/$namespace/kms/$keyset'
    | '/namespace/$namespace/kms/create'
    | '/namespace/$namespace/'
    | '/namespace/$namespace/kms/'
    | '/namespace/$namespace/services/'
    | '/namespace/$namespace/artifactory/groups/$groupId'
    | '/namespace/$namespace/artifactory/transfers/$transferId'
    | '/namespace/$namespace/services/$service/manifest'
    | '/namespace/$namespace/applications/$id'
    | '/namespace/$namespace/applications/create'
    | '/namespace/$namespace/artifactory/groups/create'
    | '/namespace/$namespace/artifactory/transfers/create'
    | '/namespace/$namespace/services/$service/create-profile'
    | '/namespace/$namespace/services/$service/settings'
    | '/namespace/$namespace/applications/'
    | '/namespace/$namespace/audit/'
    | '/namespace/$namespace/settings/'
    | '/namespace/$namespace/artifactory/groups/'
    | '/namespace/$namespace/artifactory/registry/'
    | '/namespace/$namespace/artifactory/search/'
    | '/namespace/$namespace/artifactory/transfers/'
    | '/namespace/$namespace/services/$service/'
    | '/namespace/$namespace/artifactory/registry/$groupId/$artifactId'
    | '/namespace/$namespace/services/$service/profiles/$profile'
    | '/namespace/$namespace/artifactory/groups/$groupId/edit'
    | '/namespace/$namespace/services/$service/manifest/artifacts'
    | '/namespace/$namespace/artifactory/groups/$groupId/'
    | '/namespace/$namespace/artifactory/transfers/$transferId/'
    | '/namespace/$namespace/services/$service/manifest/'
    | '/namespace/$namespace/services/$service/requests/'
    | '/namespace/$namespace/services/$service/profiles/$profile/history'
    | '/namespace/$namespace/artifactory/registry/$groupId/$artifactId/'
    | '/namespace/$namespace/services/$service/profiles/$profile/'
    | '/namespace/$namespace/services/$service/requests/$number/'
    | '/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/invitations'
    | '/api/$'
    | '/auth/code'
    | '/auth/scopes'
    | '/'
    | '/namespace/$namespace'
    | '/join/$key'
    | '/namespace/provision'
    | '/account'
    | '/namespace/$namespace/artifactory'
    | '/namespace/$namespace/invitations'
    | '/namespace/$namespace/members'
    | '/namespace/$namespace/kms/$keyset'
    | '/namespace/$namespace/kms/create'
    | '/namespace/$namespace/kms'
    | '/namespace/$namespace/services'
    | '/namespace/$namespace/applications/$id'
    | '/namespace/$namespace/applications/create'
    | '/namespace/$namespace/artifactory/groups/create'
    | '/namespace/$namespace/artifactory/transfers/create'
    | '/namespace/$namespace/services/$service/create-profile'
    | '/namespace/$namespace/services/$service/settings'
    | '/namespace/$namespace/applications'
    | '/namespace/$namespace/audit'
    | '/namespace/$namespace/settings'
    | '/namespace/$namespace/artifactory/groups'
    | '/namespace/$namespace/artifactory/registry'
    | '/namespace/$namespace/artifactory/search'
    | '/namespace/$namespace/artifactory/transfers'
    | '/namespace/$namespace/services/$service'
    | '/namespace/$namespace/artifactory/groups/$groupId/edit'
    | '/namespace/$namespace/services/$service/manifest/artifacts'
    | '/namespace/$namespace/artifactory/groups/$groupId'
    | '/namespace/$namespace/artifactory/transfers/$transferId'
    | '/namespace/$namespace/services/$service/manifest'
    | '/namespace/$namespace/services/$service/requests'
    | '/namespace/$namespace/services/$service/profiles/$profile/history'
    | '/namespace/$namespace/artifactory/registry/$groupId/$artifactId'
    | '/namespace/$namespace/services/$service/profiles/$profile'
    | '/namespace/$namespace/services/$service/requests/$number'
    | '/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version'
  id:
    | '__root__'
    | '/_authenticated'
    | '/error'
    | '/_authenticated/invitations'
    | '/api/$'
    | '/auth/code'
    | '/auth/scopes'
    | '/_authenticated/'
    | '/_authenticated/namespace/$namespace'
    | '/_authenticated/join/$key'
    | '/_authenticated/namespace/provision'
    | '/_authenticated/account/'
    | '/_authenticated/namespace/$namespace/_overview'
    | '/_authenticated/namespace/$namespace/artifactory'
    | '/_authenticated/namespace/$namespace/kms'
    | '/_authenticated/namespace/$namespace/services'
    | '/_authenticated/namespace/$namespace/_overview/applications'
    | '/_authenticated/namespace/$namespace/services/$service'
    | '/_authenticated/namespace/$namespace/_overview/invitations'
    | '/_authenticated/namespace/$namespace/_overview/members'
    | '/_authenticated/namespace/$namespace/kms/$keyset'
    | '/_authenticated/namespace/$namespace/kms/create'
    | '/_authenticated/namespace/$namespace/_overview/'
    | '/_authenticated/namespace/$namespace/kms/'
    | '/_authenticated/namespace/$namespace/services/'
    | '/_authenticated/namespace/$namespace/artifactory/groups/$groupId'
    | '/_authenticated/namespace/$namespace/artifactory/transfers/$transferId'
    | '/_authenticated/namespace/$namespace/services/$service/manifest'
    | '/_authenticated/namespace/$namespace/_overview/applications/$id'
    | '/_authenticated/namespace/$namespace/_overview/applications/create'
    | '/_authenticated/namespace/$namespace/artifactory/groups/create'
    | '/_authenticated/namespace/$namespace/artifactory/transfers/create'
    | '/_authenticated/namespace/$namespace/services/$service/create-profile'
    | '/_authenticated/namespace/$namespace/services/$service/settings'
    | '/_authenticated/namespace/$namespace/_overview/applications/'
    | '/_authenticated/namespace/$namespace/_overview/audit/'
    | '/_authenticated/namespace/$namespace/_overview/settings/'
    | '/_authenticated/namespace/$namespace/artifactory/groups/'
    | '/_authenticated/namespace/$namespace/artifactory/registry/'
    | '/_authenticated/namespace/$namespace/artifactory/search/'
    | '/_authenticated/namespace/$namespace/artifactory/transfers/'
    | '/_authenticated/namespace/$namespace/services/$service/'
    | '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId'
    | '/_authenticated/namespace/$namespace/services/$service/profiles/$profile'
    | '/_authenticated/namespace/$namespace/artifactory/groups/$groupId/edit'
    | '/_authenticated/namespace/$namespace/services/$service/manifest/artifacts'
    | '/_authenticated/namespace/$namespace/artifactory/groups/$groupId/'
    | '/_authenticated/namespace/$namespace/artifactory/transfers/$transferId/'
    | '/_authenticated/namespace/$namespace/services/$service/manifest/'
    | '/_authenticated/namespace/$namespace/services/$service/requests/'
    | '/_authenticated/namespace/$namespace/services/$service/profiles/$profile/history'
    | '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/'
    | '/_authenticated/namespace/$namespace/services/$service/profiles/$profile/'
    | '/_authenticated/namespace/$namespace/services/$service/requests/$number/'
    | '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthCodeRoute: typeof AuthCodeRoute
  AuthScopesRoute: typeof AuthScopesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/code': {
      id: '/auth/code'
      path: '/auth/code'
      fullPath: '/auth/code'
      preLoaderRoute: typeof AuthCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/scopes': {
      id: '/auth/scopes'
      path: '/auth/scopes'
      fullPath: '/auth/scopes'
      preLoaderRoute: typeof AuthScopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join/$key': {
      id: '/_authenticated/join/$key'
      path: '/join/$key'
      fullPath: '/join/$key'
      preLoaderRoute: typeof AuthenticatedJoinKeyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/namespace/$namespace': {
      id: '/_authenticated/namespace/$namespace'
      path: '/namespace/$namespace'
      fullPath: '/namespace/$namespace'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/namespace/provision': {
      id: '/_authenticated/namespace/provision'
      path: '/namespace/provision'
      fullPath: '/namespace/provision'
      preLoaderRoute: typeof AuthenticatedNamespaceProvisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview': {
      id: '/_authenticated/namespace/$namespace/_overview'
      path: ''
      fullPath: '/namespace/$namespace'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory': {
      id: '/_authenticated/namespace/$namespace/artifactory'
      path: '/artifactory'
      fullPath: '/namespace/$namespace/artifactory'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/kms': {
      id: '/_authenticated/namespace/$namespace/kms'
      path: '/kms'
      fullPath: '/namespace/$namespace/kms'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceKmsRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services': {
      id: '/_authenticated/namespace/$namespace/services'
      path: '/services'
      fullPath: '/namespace/$namespace/services'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview/': {
      id: '/_authenticated/namespace/$namespace/_overview/'
      path: '/'
      fullPath: '/namespace/$namespace/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceOverviewRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview/applications': {
      id: '/_authenticated/namespace/$namespace/_overview/applications'
      path: '/applications'
      fullPath: '/namespace/$namespace/applications'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceOverviewRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview/invitations': {
      id: '/_authenticated/namespace/$namespace/_overview/invitations'
      path: '/invitations'
      fullPath: '/namespace/$namespace/invitations'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewInvitationsRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceOverviewRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview/members': {
      id: '/_authenticated/namespace/$namespace/_overview/members'
      path: '/members'
      fullPath: '/namespace/$namespace/members'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewMembersRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceOverviewRouteRoute
    }
    '/_authenticated/namespace/$namespace/kms/': {
      id: '/_authenticated/namespace/$namespace/kms/'
      path: '/'
      fullPath: '/namespace/$namespace/kms/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceKmsIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceKmsRouteRoute
    }
    '/_authenticated/namespace/$namespace/kms/$keyset': {
      id: '/_authenticated/namespace/$namespace/kms/$keyset'
      path: '/$keyset'
      fullPath: '/namespace/$namespace/kms/$keyset'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceKmsKeysetRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceKmsRouteRoute
    }
    '/_authenticated/namespace/$namespace/kms/create': {
      id: '/_authenticated/namespace/$namespace/kms/create'
      path: '/create'
      fullPath: '/namespace/$namespace/kms/create'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceKmsCreateRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceKmsRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/': {
      id: '/_authenticated/namespace/$namespace/services/'
      path: '/'
      fullPath: '/namespace/$namespace/services/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service': {
      id: '/_authenticated/namespace/$namespace/services/$service'
      path: '/$service'
      fullPath: '/namespace/$namespace/services/$service'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview/applications/': {
      id: '/_authenticated/namespace/$namespace/_overview/applications/'
      path: '/'
      fullPath: '/namespace/$namespace/applications/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview/applications/$id': {
      id: '/_authenticated/namespace/$namespace/_overview/applications/$id'
      path: '/$id'
      fullPath: '/namespace/$namespace/applications/$id'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview/applications/create': {
      id: '/_authenticated/namespace/$namespace/_overview/applications/create'
      path: '/create'
      fullPath: '/namespace/$namespace/applications/create'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview/audit/': {
      id: '/_authenticated/namespace/$namespace/_overview/audit/'
      path: '/audit'
      fullPath: '/namespace/$namespace/audit/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewAuditIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceOverviewRouteRoute
    }
    '/_authenticated/namespace/$namespace/_overview/settings/': {
      id: '/_authenticated/namespace/$namespace/_overview/settings/'
      path: '/settings'
      fullPath: '/namespace/$namespace/settings/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceOverviewSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceOverviewRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/groups/': {
      id: '/_authenticated/namespace/$namespace/artifactory/groups/'
      path: '/groups'
      fullPath: '/namespace/$namespace/artifactory/groups/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/groups/$groupId': {
      id: '/_authenticated/namespace/$namespace/artifactory/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/namespace/$namespace/artifactory/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/groups/create': {
      id: '/_authenticated/namespace/$namespace/artifactory/groups/create'
      path: '/groups/create'
      fullPath: '/namespace/$namespace/artifactory/groups/create'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/registry/': {
      id: '/_authenticated/namespace/$namespace/artifactory/registry/'
      path: '/registry'
      fullPath: '/namespace/$namespace/artifactory/registry/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/search/': {
      id: '/_authenticated/namespace/$namespace/artifactory/search/'
      path: '/search'
      fullPath: '/namespace/$namespace/artifactory/search/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactorySearchIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/transfers/': {
      id: '/_authenticated/namespace/$namespace/artifactory/transfers/'
      path: '/transfers'
      fullPath: '/namespace/$namespace/artifactory/transfers/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/transfers/$transferId': {
      id: '/_authenticated/namespace/$namespace/artifactory/transfers/$transferId'
      path: '/transfers/$transferId'
      fullPath: '/namespace/$namespace/artifactory/transfers/$transferId'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/transfers/create': {
      id: '/_authenticated/namespace/$namespace/artifactory/transfers/create'
      path: '/transfers/create'
      fullPath: '/namespace/$namespace/artifactory/transfers/create'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/': {
      id: '/_authenticated/namespace/$namespace/services/$service/'
      path: '/'
      fullPath: '/namespace/$namespace/services/$service/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/create-profile': {
      id: '/_authenticated/namespace/$namespace/services/$service/create-profile'
      path: '/create-profile'
      fullPath: '/namespace/$namespace/services/$service/create-profile'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/manifest': {
      id: '/_authenticated/namespace/$namespace/services/$service/manifest'
      path: '/manifest'
      fullPath: '/namespace/$namespace/services/$service/manifest'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/settings': {
      id: '/_authenticated/namespace/$namespace/services/$service/settings'
      path: '/settings'
      fullPath: '/namespace/$namespace/services/$service/settings'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/groups/$groupId/': {
      id: '/_authenticated/namespace/$namespace/artifactory/groups/$groupId/'
      path: '/'
      fullPath: '/namespace/$namespace/artifactory/groups/$groupId/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/groups/$groupId/edit': {
      id: '/_authenticated/namespace/$namespace/artifactory/groups/$groupId/edit'
      path: '/edit'
      fullPath: '/namespace/$namespace/artifactory/groups/$groupId/edit'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId': {
      id: '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId'
      path: '/registry/$groupId/$artifactId'
      fullPath: '/namespace/$namespace/artifactory/registry/$groupId/$artifactId'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/transfers/$transferId/': {
      id: '/_authenticated/namespace/$namespace/artifactory/transfers/$transferId/'
      path: '/'
      fullPath: '/namespace/$namespace/artifactory/transfers/$transferId/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/manifest/': {
      id: '/_authenticated/namespace/$namespace/services/$service/manifest/'
      path: '/'
      fullPath: '/namespace/$namespace/services/$service/manifest/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/manifest/artifacts': {
      id: '/_authenticated/namespace/$namespace/services/$service/manifest/artifacts'
      path: '/artifacts'
      fullPath: '/namespace/$namespace/services/$service/manifest/artifacts'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/profiles/$profile': {
      id: '/_authenticated/namespace/$namespace/services/$service/profiles/$profile'
      path: '/profiles/$profile'
      fullPath: '/namespace/$namespace/services/$service/profiles/$profile'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/requests/': {
      id: '/_authenticated/namespace/$namespace/services/$service/requests/'
      path: '/requests'
      fullPath: '/namespace/$namespace/services/$service/requests/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/': {
      id: '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/'
      path: '/'
      fullPath: '/namespace/$namespace/artifactory/registry/$groupId/$artifactId/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/profiles/$profile/': {
      id: '/_authenticated/namespace/$namespace/services/$service/profiles/$profile/'
      path: '/'
      fullPath: '/namespace/$namespace/services/$service/profiles/$profile/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/profiles/$profile/history': {
      id: '/_authenticated/namespace/$namespace/services/$service/profiles/$profile/history'
      path: '/history'
      fullPath: '/namespace/$namespace/services/$service/profiles/$profile/history'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRoute
    }
    '/_authenticated/namespace/$namespace/services/$service/requests/$number/': {
      id: '/_authenticated/namespace/$namespace/services/$service/requests/$number/'
      path: '/requests/$number'
      fullPath: '/namespace/$namespace/services/$service/requests/$number/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRoute
    }
    '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version/': {
      id: '/_authenticated/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version/'
      path: '/$version'
      fullPath: '/namespace/$namespace/artifactory/registry/$groupId/$artifactId/$version/'
      preLoaderRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRouteImport
      parentRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRoute
    }
  }
}

interface AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteChildren {
  AuthenticatedNamespaceNamespaceOverviewApplicationsIdRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIdRoute
  AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRoute
  AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRoute
}

const AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteChildren: AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceOverviewApplicationsIdRoute:
      AuthenticatedNamespaceNamespaceOverviewApplicationsIdRoute,
    AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRoute:
      AuthenticatedNamespaceNamespaceOverviewApplicationsCreateRoute,
    AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRoute:
      AuthenticatedNamespaceNamespaceOverviewApplicationsIndexRoute,
  }

const AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceOverviewRouteRouteChildren {
  AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute: typeof AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceOverviewInvitationsRoute: typeof AuthenticatedNamespaceNamespaceOverviewInvitationsRoute
  AuthenticatedNamespaceNamespaceOverviewMembersRoute: typeof AuthenticatedNamespaceNamespaceOverviewMembersRoute
  AuthenticatedNamespaceNamespaceOverviewIndexRoute: typeof AuthenticatedNamespaceNamespaceOverviewIndexRoute
  AuthenticatedNamespaceNamespaceOverviewAuditIndexRoute: typeof AuthenticatedNamespaceNamespaceOverviewAuditIndexRoute
  AuthenticatedNamespaceNamespaceOverviewSettingsIndexRoute: typeof AuthenticatedNamespaceNamespaceOverviewSettingsIndexRoute
}

const AuthenticatedNamespaceNamespaceOverviewRouteRouteChildren: AuthenticatedNamespaceNamespaceOverviewRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRoute:
      AuthenticatedNamespaceNamespaceOverviewApplicationsRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceOverviewInvitationsRoute:
      AuthenticatedNamespaceNamespaceOverviewInvitationsRoute,
    AuthenticatedNamespaceNamespaceOverviewMembersRoute:
      AuthenticatedNamespaceNamespaceOverviewMembersRoute,
    AuthenticatedNamespaceNamespaceOverviewIndexRoute:
      AuthenticatedNamespaceNamespaceOverviewIndexRoute,
    AuthenticatedNamespaceNamespaceOverviewAuditIndexRoute:
      AuthenticatedNamespaceNamespaceOverviewAuditIndexRoute,
    AuthenticatedNamespaceNamespaceOverviewSettingsIndexRoute:
      AuthenticatedNamespaceNamespaceOverviewSettingsIndexRoute,
  }

const AuthenticatedNamespaceNamespaceOverviewRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceOverviewRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceOverviewRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteChildren {
  AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRoute
  AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRoute
}

const AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteChildren: AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRoute:
      AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdEditRoute,
    AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRoute:
      AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdIndexRoute,
  }

const AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteChildren {
  AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRoute
}

const AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteChildren: AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRoute:
      AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdIndexRoute,
  }

const AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteChildren {
  AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRoute
  AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRoute
}

const AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteChildren: AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRoute:
      AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdIndexRoute,
    AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRoute:
      AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdVersionIndexRoute,
  }

const AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceArtifactoryRouteRouteChildren {
  AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRoute
  AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRoute
  AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRoute
  AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRoute
  AuthenticatedNamespaceNamespaceArtifactorySearchIndexRoute: typeof AuthenticatedNamespaceNamespaceArtifactorySearchIndexRoute
  AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRoute
  AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteWithChildren
}

const AuthenticatedNamespaceNamespaceArtifactoryRouteRouteChildren: AuthenticatedNamespaceNamespaceArtifactoryRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRoute:
      AuthenticatedNamespaceNamespaceArtifactoryGroupsGroupIdRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRoute:
      AuthenticatedNamespaceNamespaceArtifactoryTransfersTransferIdRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRoute:
      AuthenticatedNamespaceNamespaceArtifactoryGroupsCreateRoute,
    AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRoute:
      AuthenticatedNamespaceNamespaceArtifactoryTransfersCreateRoute,
    AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRoute:
      AuthenticatedNamespaceNamespaceArtifactoryGroupsIndexRoute,
    AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRoute:
      AuthenticatedNamespaceNamespaceArtifactoryRegistryIndexRoute,
    AuthenticatedNamespaceNamespaceArtifactorySearchIndexRoute:
      AuthenticatedNamespaceNamespaceArtifactorySearchIndexRoute,
    AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRoute:
      AuthenticatedNamespaceNamespaceArtifactoryTransfersIndexRoute,
    AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRoute:
      AuthenticatedNamespaceNamespaceArtifactoryRegistryGroupIdArtifactIdRouteRouteWithChildren,
  }

const AuthenticatedNamespaceNamespaceArtifactoryRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceArtifactoryRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceArtifactoryRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceKmsRouteRouteChildren {
  AuthenticatedNamespaceNamespaceKmsKeysetRoute: typeof AuthenticatedNamespaceNamespaceKmsKeysetRoute
  AuthenticatedNamespaceNamespaceKmsCreateRoute: typeof AuthenticatedNamespaceNamespaceKmsCreateRoute
  AuthenticatedNamespaceNamespaceKmsIndexRoute: typeof AuthenticatedNamespaceNamespaceKmsIndexRoute
}

const AuthenticatedNamespaceNamespaceKmsRouteRouteChildren: AuthenticatedNamespaceNamespaceKmsRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceKmsKeysetRoute:
      AuthenticatedNamespaceNamespaceKmsKeysetRoute,
    AuthenticatedNamespaceNamespaceKmsCreateRoute:
      AuthenticatedNamespaceNamespaceKmsCreateRoute,
    AuthenticatedNamespaceNamespaceKmsIndexRoute:
      AuthenticatedNamespaceNamespaceKmsIndexRoute,
  }

const AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceKmsRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceKmsRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteChildren {
  AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRoute
  AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRoute
}

const AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteChildren: AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRoute:
      AuthenticatedNamespaceNamespaceServicesServiceManifestArtifactsRoute,
    AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRoute:
      AuthenticatedNamespaceNamespaceServicesServiceManifestIndexRoute,
  }

const AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteChildren {
  AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRoute
  AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRoute
}

const AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteChildren: AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRoute:
      AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileHistoryRoute,
    AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRoute:
      AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileIndexRoute,
  }

const AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceServicesServiceRouteRouteChildren {
  AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute
  AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute
  AuthenticatedNamespaceNamespaceServicesServiceIndexRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceIndexRoute
  AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute
  AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRoute
}

const AuthenticatedNamespaceNamespaceServicesServiceRouteRouteChildren: AuthenticatedNamespaceNamespaceServicesServiceRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRoute:
      AuthenticatedNamespaceNamespaceServicesServiceManifestRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute:
      AuthenticatedNamespaceNamespaceServicesServiceCreateProfileRoute,
    AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute:
      AuthenticatedNamespaceNamespaceServicesServiceSettingsRoute,
    AuthenticatedNamespaceNamespaceServicesServiceIndexRoute:
      AuthenticatedNamespaceNamespaceServicesServiceIndexRoute,
    AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRoute:
      AuthenticatedNamespaceNamespaceServicesServiceProfilesProfileRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute:
      AuthenticatedNamespaceNamespaceServicesServiceRequestsIndexRoute,
    AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRoute:
      AuthenticatedNamespaceNamespaceServicesServiceRequestsNumberIndexRoute,
  }

const AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceServicesServiceRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceServicesServiceRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceServicesRouteRouteChildren {
  AuthenticatedNamespaceNamespaceServicesServiceRouteRoute: typeof AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceServicesIndexRoute: typeof AuthenticatedNamespaceNamespaceServicesIndexRoute
}

const AuthenticatedNamespaceNamespaceServicesRouteRouteChildren: AuthenticatedNamespaceNamespaceServicesRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceServicesServiceRouteRoute:
      AuthenticatedNamespaceNamespaceServicesServiceRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceServicesIndexRoute:
      AuthenticatedNamespaceNamespaceServicesIndexRoute,
  }

const AuthenticatedNamespaceNamespaceServicesRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceServicesRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceServicesRouteRouteChildren,
  )

interface AuthenticatedNamespaceNamespaceRouteRouteChildren {
  AuthenticatedNamespaceNamespaceOverviewRouteRoute: typeof AuthenticatedNamespaceNamespaceOverviewRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceArtifactoryRouteRoute: typeof AuthenticatedNamespaceNamespaceArtifactoryRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceKmsRouteRoute: typeof AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren
  AuthenticatedNamespaceNamespaceServicesRouteRoute: typeof AuthenticatedNamespaceNamespaceServicesRouteRouteWithChildren
}

const AuthenticatedNamespaceNamespaceRouteRouteChildren: AuthenticatedNamespaceNamespaceRouteRouteChildren =
  {
    AuthenticatedNamespaceNamespaceOverviewRouteRoute:
      AuthenticatedNamespaceNamespaceOverviewRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceArtifactoryRouteRoute:
      AuthenticatedNamespaceNamespaceArtifactoryRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceKmsRouteRoute:
      AuthenticatedNamespaceNamespaceKmsRouteRouteWithChildren,
    AuthenticatedNamespaceNamespaceServicesRouteRoute:
      AuthenticatedNamespaceNamespaceServicesRouteRouteWithChildren,
  }

const AuthenticatedNamespaceNamespaceRouteRouteWithChildren =
  AuthenticatedNamespaceNamespaceRouteRoute._addFileChildren(
    AuthenticatedNamespaceNamespaceRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedNamespaceNamespaceRouteRoute: typeof AuthenticatedNamespaceNamespaceRouteRouteWithChildren
  AuthenticatedJoinKeyRoute: typeof AuthenticatedJoinKeyRoute
  AuthenticatedNamespaceProvisionRoute: typeof AuthenticatedNamespaceProvisionRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedNamespaceNamespaceRouteRoute:
    AuthenticatedNamespaceNamespaceRouteRouteWithChildren,
  AuthenticatedJoinKeyRoute: AuthenticatedJoinKeyRoute,
  AuthenticatedNamespaceProvisionRoute: AuthenticatedNamespaceProvisionRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthCodeRoute: AuthCodeRoute,
  AuthScopesRoute: AuthScopesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
