## Account events ##

audit.event.account.updated=Account was updated
audit.event.account.deleted=Account was deleted

## Namespace events ##

audit.event.namespace.created=Namespace was created
audit.event.namespace.renamed=Namespace was renamed from ''{0}'' to ''{1}''
audit.event.namespace.deleted=Namespace was deleted
audit.event.namespace.member-added=Member was added with {1} role
audit.event.namespace.member-updated=Member role was changed to {1}
audit.event.namespace.member-removed=Member was removed
audit.event.namespace.application-created=Application ''{0}'' was created
audit.event.namespace.application-reset=Credentials were reset for ''{0}'' application
audit.event.namespace.application-updated=Application ''{0}'' was updated
audit.event.namespace.application-removed=Application ''{0}'' was removed

## Invitation events ##

audit.event.invitation.created=Invitation was sent
audit.event.invitation.accepted=Invitation was accepted
audit.event.invitation.canceled=Invitation was canceled

## Service events ##

audit.event.service.created=Service was created
audit.event.service.renamed=Service was renamed from ''{0}'' to ''{1}''
audit.event.service.published=Service artifacts were published
audit.event.service.deleted=Service was deleted

## Profile events ##

audit.event.profile.created=Profile ''{0}'' was created
audit.event.profile.updated=Profile ''{0}'' was updated
audit.event.profile.deleted=Profile ''{0}'' was deleted
audit.event.profile.changes-applied=Configuration changes were applied at revision {0}

## Keyset events ##

audit.event.keyset.created=Keyset was created
audit.event.keyset.rotated=Keyset was rotated
audit.event.keyset.deleted=Keyset was successfully removed
audit.event.keyset.reactivated=Key ''{0}'' within a keyset was reactivated
audit.event.keyset.deactivated=Key ''{0}'' within a keyset was disabled
audit.event.keyset.compromised=Key ''{0}'' within a keyset was marked as compromised
audit.event.keyset.restored=Key ''{0}'' within a keyset was restored
audit.event.keyset.destroyed=Key ''{0}'' within a keyset was scheduled for destruction

## Artifact events ##

audit.event.artifact-version.release-created=Artifact release started for {0}
audit.event.artifact-version.release-completed=Artifact release completed for {0}
audit.event.artifact-version.release-failed=Artifact release failed for {0}
