spring:
  application:
    name: konfigyr-identity

  cache:
    cache-names: crypto-keysets
    caffeine:
      spec: expireAfterWrite=1h

  liquibase:
    change-log: classpath:migrations/changelog.xml
    contexts: identity

  messages:
    basename: messages/messages, messages/mail

  mail:
    sender:
      name: Konfigyr
      email: noreply@konfigyr.com

  security:
    oauth2:
      client:
        provider:
          github:
            user-name-attribute: email

  web:
    resources:
      static-locations: classpath:/static/, classpath:/dist/

konfigyr:
  identity:
    authorization:
      client-id: konfigyr
      audiences:
        - konfigyr-api
      redirect-uris:
        - "http://127.0.0.1:8080/login/oauth2/code/konfigyr"
        - "https://oauth.pstmn.io/v1/callback"
      post-logout-redirect-uris:
        - "http://127.0.0.1:8080/"
      cache:
        spec: expireAfterWrite=5m,maximumSize=100
      token:
        access-token-time-to-live: 15m
        refresh-token-time-to-live: 7d
        id-token-signature-algorithm: PS256
      namespace-token-settings:
        agent:
          access-token-time-to-live: 1h
          refresh-token-time-to-live: 7d
        service-account:
          access-token-time-to-live: 20m
          refresh-token-time-to-live: 7d
        pipeline:
          access-token-time-to-live: 30m
          refresh-token-time-to-live: 1d

management:
  info:
    java:
      enabled: true
    build:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics

  endpoint:
    health:
      show-details: when-authorized

  observations:
    annotations:
      enabled: true

logging:
  pattern:
    console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr([%-20thread]) %clr(%-5level) [%mdc] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %marker %m%n'
