package com.konfigyr.audit;

import com.konfigyr.data.CursorPage;
import com.konfigyr.data.CursorPageable;
import com.konfigyr.data.Routines;
import com.konfigyr.data.SettableRecord;
import com.konfigyr.data.converter.JsonbConverter;
import com.konfigyr.entity.EntityId;
import com.konfigyr.support.SearchQuery;
import lombok.extern.slf4j.Slf4j;
import org.jmolecules.ddd.annotation.Repository;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jspecify.annotations.NullMarked;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.json.JsonMapper;

import java.time.OffsetDateTime;
import java.util.*;

import static com.konfigyr.data.tables.AuditEvents.AUDIT_EVENTS;

/**
 * Repository for persisting and querying the Konfigyr audit log.
 * <p>
 * Accepts {@link AuditEvent} for writes and returns {@link AuditRecord} for reads.
 * The identifier (UUID v7) and the creation timestamp are generated by the database upon
 * insertion — the caller is never responsible for supplying them.
 * <p>
 * Read operations support cursor-based, bidirectional pagination using an opaque
 * {@link AuditCursorToken} that encodes the last-seen record position. Filter criteria
 * are expressed via {@link SearchQuery} using the constants defined on {@link AuditRecord}.
 * <p>
 * The underlying storage is a time-partitioned table (monthly partitions). Event details
 * are serialized as JSONB and deserialized back to a {@code Map} on read; serialization
 * failures are logged and silently produce {@literal null} rather than propagating, so that
 * a malformed payload never prevents the rest of the audit log from being served.
 *
 * @author Vladimir Spasic
 * @since 1.0.0
 * @see AuditEvent
 * @see AuditRecord
 * @see AuditCursorToken
 */
@Slf4j
@NullMarked
@Repository
public class AuditEventRepository {

	static final List<Field<?>> AUDIT_EVENT_FIELDS = List.of(
			AUDIT_EVENTS.ID,
			AUDIT_EVENTS.NAMESPACE_ID,
			AUDIT_EVENTS.ENTITY_TYPE,
			AUDIT_EVENTS.ENTITY_ID,
			AUDIT_EVENTS.EVENT_TYPE,
			AUDIT_EVENTS.ACTOR_ID,
			AUDIT_EVENTS.ACTOR_TYPE,
			AUDIT_EVENTS.ACTOR_NAME,
			AUDIT_EVENTS.DETAILS,
			AUDIT_EVENTS.CREATED_AT
	);

	private final DSLContext context;
	private final Converter<JSONB, Map<String, Object>> detailsConverter;

	public AuditEventRepository(DSLContext context, JsonMapper jsonMapper) {
		this.context = context;
		this.detailsConverter = JsonbConverter.create(jsonMapper, jsonMapper.constructType(Object.class));
	}

	/**
	 * Inserts a new {@link AuditEvent} into the audit log. The database generates the identifier and
	 * timestamp upon insertion.
	 *
	 * @param event the audit event to persist, must not be {@literal null}
	 */
	@Transactional(label = "audit.insert-event")
	public void insert(AuditEvent event) {
		context.insertInto(AUDIT_EVENTS)
				.set(
						SettableRecord.of(context, AUDIT_EVENTS)
								.set(AUDIT_EVENTS.NAMESPACE_ID, event.namespaceId(), EntityId::get)
								.set(AUDIT_EVENTS.ENTITY_TYPE, event.entityType())
								.set(AUDIT_EVENTS.ENTITY_ID, event.entityId().get())
								.set(AUDIT_EVENTS.EVENT_TYPE, event.eventType())
								.set(AUDIT_EVENTS.ACTOR_ID, event.actor().id())
								.set(AUDIT_EVENTS.ACTOR_TYPE, event.actor().type())
								.set(AUDIT_EVENTS.ACTOR_NAME, event.actor().name())
								.set(AUDIT_EVENTS.DETAILS, event.details(), detailsConverter)
								.get()
				)
				.execute();
	}

	/**
	 * Finds audit records matching the given query with cursor-based pagination.
	 *
	 * @param query the search query containing filter criteria, must not be {@literal null}
	 * @param pageable the pagination parameters, must not be {@literal null}
	 * @return a cursor page of matching audit records, never {@literal null}
	 */
	@Transactional(label = "audit.find-events", readOnly = true)
	public CursorPage<AuditRecord> find(SearchQuery query, CursorPageable pageable) {
		final List<Condition> conditions = buildFilterConditions(query);

		if (pageable.isUnpaged()) {
			return CursorPage.of(
					createQuery(DSL.and(conditions))
							.orderBy(AUDIT_EVENTS.CREATED_AT.desc())
							.fetch(this::toAuditRecord)
			);
		}

		final AuditCursorToken token = AuditCursorToken.decode(pageable);
		final boolean isReversed = token != null && token.reversed();
		final SortOrder sortOrder = isReversed ? SortOrder.ASC : SortOrder.DESC;

		if (token != null) {
			if (sortOrder == SortOrder.DESC) {
				conditions.add(AUDIT_EVENTS.ID.lessThan(token.identifier()));
				conditions.add(AUDIT_EVENTS.CREATED_AT.lessThan(token.timestamp()));
			} else {
				conditions.add(AUDIT_EVENTS.ID.greaterThan(token.identifier()));
				conditions.add(AUDIT_EVENTS.CREATED_AT.greaterThan(token.timestamp()));
			}
		}

		final List<Record> results = createQuery(DSL.and(conditions))
				.orderBy(AUDIT_EVENTS.CREATED_AT.sort(sortOrder), AUDIT_EVENTS.ID.sort(sortOrder))
				.limit(pageable.size() + 1)
				.fetch();

		final boolean hasMore = results.size() > pageable.size();
		final List<Record> content = hasMore ? results.subList(0, pageable.size()) : results;

		if (isReversed) {
			Collections.reverse(content);
		}

		CursorPageable nextPageable = null;
		CursorPageable previousPageable = null;

		if (hasMore || isReversed) {
			final Record lastItem = content.getLast();
			nextPageable = encodeNextCursor(
					lastItem.get(AUDIT_EVENTS.ID),
					lastItem.get(AUDIT_EVENTS.CREATED_AT),
					pageable.size()
			);
		}

		if (pageable.token() != null && (!isReversed || hasMore)) {
			final Record firstItem = content.getFirst();
			previousPageable = encodePreviousCursor(
					firstItem.get(AUDIT_EVENTS.ID),
					firstItem.get(AUDIT_EVENTS.CREATED_AT),
					pageable.size()
			);
		}

		return CursorPage.of(content, nextPageable, previousPageable)
				.map(this::toAuditRecord);
	}

	@Transactional(label = "audit.create-partition")
	@Scheduled(cron = "${konfigyr.audit.partitioning-cron:0 0 0 * * *}")
	void createPartition() {
		Routines.createAuditEventsPartition(context.configuration(), OffsetDateTime.now().plusDays(1));
	}

	private SelectConditionStep<Record> createQuery(Condition condition) {
		return context.select(AUDIT_EVENT_FIELDS)
				.from(AUDIT_EVENTS)
				.where(condition);
	}

	private AuditRecord toAuditRecord(Record record) {
		return new AuditRecord(
				record.get(AUDIT_EVENTS.ID).toString(),
				record.get(AUDIT_EVENTS.NAMESPACE_ID, EntityId.class),
				record.get(AUDIT_EVENTS.ENTITY_TYPE),
				record.get(AUDIT_EVENTS.ENTITY_ID, EntityId.class),
				record.get(AUDIT_EVENTS.EVENT_TYPE),
				new Actor(
						record.get(AUDIT_EVENTS.ACTOR_ID),
						record.get(AUDIT_EVENTS.ACTOR_TYPE),
						record.get(AUDIT_EVENTS.ACTOR_NAME)
				),
				record.get(AUDIT_EVENTS.DETAILS, detailsConverter),
				record.get(AUDIT_EVENTS.CREATED_AT)
		);
	}

	private static List<Condition> buildFilterConditions(SearchQuery query) {
		final List<Condition> conditions = new ArrayList<>();

		query.criteria(AuditRecord.NAMESPACE_ID_CRITERIA).ifPresent(namespaceId -> conditions.add(
				AUDIT_EVENTS.NAMESPACE_ID.eq(namespaceId.get())
		));

		query.criteria(AuditRecord.ENTITY_TYPE_CRITERIA).ifPresent(entityType -> conditions.add(
				AUDIT_EVENTS.ENTITY_TYPE.eq(entityType)
		));

		query.criteria(AuditRecord.ENTITY_ID_CRITERIA).ifPresent(entityId -> conditions.add(
				AUDIT_EVENTS.ENTITY_ID.eq(entityId.get())
		));

		query.criteria(AuditRecord.EVENT_TYPE_CRITERIA).ifPresent(eventType -> conditions.add(
				AUDIT_EVENTS.EVENT_TYPE.eq(eventType)
		));

		query.criteria(AuditRecord.ACTOR_ID_CRITERIA).ifPresent(actorId -> conditions.add(
				AUDIT_EVENTS.ACTOR_ID.eq(actorId)
		));

		query.criteria(AuditRecord.FROM_CRITERIA).ifPresent(from -> conditions.add(
				AUDIT_EVENTS.CREATED_AT.greaterOrEqual(from)
		));

		query.criteria(AuditRecord.TO_CRITERIA).ifPresent(to -> conditions.add(
				AUDIT_EVENTS.CREATED_AT.lessOrEqual(to)
		));

		if (conditions.isEmpty()) {
			conditions.add(DSL.trueCondition());
		}

		return conditions;
	}

	private static CursorPageable encodeNextCursor(UUID identifier, OffsetDateTime timestamp, int size) {
		return CursorPageable.of(
				AuditCursorToken.of(identifier, timestamp).value(),
				size
		);
	}

	private static CursorPageable encodePreviousCursor(UUID identifier, OffsetDateTime timestamp, int size) {
		return CursorPageable.of(
				AuditCursorToken.of(identifier, timestamp, true).value(),
				size
		);
	}

}
