name: CI

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    strategy:
      matrix:
        os:
          - id: ubuntu-latest
            name: Linux
          - id: windows-latest
            name: Windows
        jdk:
          - version: 21
      fail-fast: false
    name: 'CI | ${{ matrix.os.name}} | Java ${{ matrix.jdk.version}}'
    runs-on: ${{ matrix.os.id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.2

      - name: Set up JDK ${{ matrix.jdk.version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk.version }}
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        env:
          CI: 'true'
        run: ./gradlew build

      - name: Test Reports
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
